version: '3'
services:
  web:
    build:
      dockerfile: ./docker/php/Dockerfile
    ports: 
      - 8080:80
    volumes:
      - ./public:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db: 
    image: mysql
    restart: always
    volumes: 
      - ./docker/data/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: example
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: example


  adminer:
    image: adminer
    restart: always
    ports: 
      - 8025:8080